# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Title
#' @param string the string (a part of a triple pattern) to label
#' @param language the language in which to return the label (defaults to "en")
#' @param endpoint the SPARQL endpoint that is being queried (defaults to "Wikidata")
#' @param labelling_prop the name of the labelling property, for instance "skos:prefLabel". Defaults to "rdfs:label"
#' This function takes a component of a triple pattern as input and returns (if it exists) a corresponding human-readable label.
#' @return the label corresponding to the string
#' @export
#' @examples
#' sequins::get_label("wd:Q152088",language="en")
#' sequins::get_label("'David Bowie'")
#' sequins::get_label('"John Doe"')
#' sequins::get_label("?item")
get_label=function(string, language="en",endpoint="Wikidata", labelling_prop="rdfs:label"){
  # if the string starts with "?" or "'" or '"'
  if(stringr::str_detect(string,"^\\?|\\'")|stringr::str_detect(string,'^\\"')){
    return(string)
  }
  result=spq_init() %>% 
    spq_add(glue::glue("{string} {labelling_prop} ?string_label")) %>% 
    spq_mutate(languages=lang(string_label)) %>% 
    spq_perform(endpoint=endpoint) %>% 
    dplyr::filter(languages==language) %>% 
    .$string_label
  return(result)
}

