# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' This function takes a component of a triple pattern as input and returns (if it exists) a corresponding human-readable label.
#' @param string the string (a part of a triple pattern) to label
#' @param language the language in which to return the label (defaults to "en")
#' @param endpoint the SPARQL endpoint that is being queried (defaults to "wikidata")
#' @param label_property the name of the labelling property, for instance "skos:prefLabel". Defaults to "rdfs:label". If the endpoint is one of the usual glitter endpoints (see glitter::usual_endpoints) the labelling property is set accordingly.
#' @return the label corresponding to the string
#' @export
#' @examples
#' get_label_1("wdt:P31")
#' get_label_1("{wd:Q144 wd:Q146 wd:Q780}")
get_label_1=function(string, language="en",endpoint="wikidata", label_property="rdfs:label"){
        if(!glitter:::is_prefixed(string)){
          return(string)
        }
        strings=print_values(string)
        results=rep(NA,length(strings))
        for (i in 1:length(strings)){
            string=strings[i]
            string=glitter:::str_replace(string,
                                         "(^wdt\\:)|(^p\\:)|(^ps\\:)|(^pq\\:)",
                                         "wd:")
            result=glitter::spq_init(endpoint=endpoint) %>% 
              glitter::spq_add(glue::glue("{string} {label_property} ?string_label")) %>% 
              glitter::spq_mutate(languages=lang(string_label)) %>% 
              glitter::spq_perform() %>% 
              dplyr::filter(languages==language) %>%
              .$string_label
            if(length(result)==0){result=string}
            results[i]=result
        }
        result=paste0(results,collapse="\n")
        return(result)
}
