# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' This function takes a component of a triple pattern as input and returns (if it exists) a corresponding human-readable label.
#' @param string the string (a part of a triple pattern) to label
#' @param language the language in which to return the label (defaults to "en")
#' @param endpoint the SPARQL endpoint that is being queried (defaults to "wikidata")
#' @param label_property the name of the labelling property, for instance "skos:prefLabel". Defaults to "rdfs:label". If the endpoint is one of the usual glitter endpoints (see glitter::usual_endpoints) the labelling property is set accordingly.
#' @return the label corresponding to the string
#' @export
#' @examples
#' get_label("wd:Q152088",language="en")
#' get_label("wd:Q152088",language="fr")
#' get_label(c("wdt:P31","wdt:P625","'David Bowie'","?item"), language="fr")
#' get_label("hal:structure",endpoint="hal")
get_label=function(string, language="en",endpoint="wikidata", label_property="rdfs:label"){
  if(endpoint %in% glitter::usual_endpoints$name){
    index_endpoint=which(glitter::usual_endpoints$name==endpoint)
    label_property=glitter::usual_endpoints$label_property[index_endpoint]
  }
  result=purrr::map_chr(string,
                        get_label_1,
                        language=language,
                        endpoint=endpoint,
                        label_property=label_property)
  return(result)
}
