# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' In query graphs, replaces items and properties identifiers with labels
#' @param graph query graph
#' @param endpoint the endpoint
#' @param language the language of labels. Defaults to English ("en")
#' @param label_property the property used to label. Defaults to "rdfs:label"
#' @return the graph with names of nodes and edges corresponding to labels (and not identifiers)
#' 
#' @noRd
graph_label <- function(graph, endpoint, label_property="rdfs:label", language="en"){
    graph=graph %>% 
      tidygraph::activate(nodes) %>% 
      dplyr::mutate(label=purrr::map_chr(label,
                                         sequins::get_label,
                                         language=language,
                                         label_property=label_property, 
                                         endpoint=endpoint))
    graph=graph %>% 
      tidygraph::activate(edges) %>% 
      dplyr::mutate(label=purrr::map_chr(link,
                                         sequins::get_label,
                                         language=language, 
                                         label_property=label_property, 
                                         endpoint=endpoint))
    return(graph)
}
