# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' A graph depicting the query
#' @param query a query as returned by glitter (before call to spq_perform)
#' @param labelling whether to label the identifiers in the graph
#' @param language the language in which to label. Defaults to English ("en")
#' @param set_labels a named vector to replace some elements with a user-defined label. For instance, c("hal:structure"="id de labo")
#' @return
#' a tidygraph
#' @export
#'
graph_query <- function(query, labelling=FALSE, language="en", set_labels=NULL){
  # Create graph from triples
  triples=query$triples %>%
    dplyr::mutate(data=purrr::map(triple,glitter:::decompose_triple_pattern)) %>%  
    dplyr::mutate(from=purrr::map_chr(data,~.x$subject),
                  to  =purrr::map_chr(data,~.x$object),
                  link=purrr::map_chr(data,~.x$verb)) %>% 
    dplyr::select(triple, required, from, to, link)
  if(!all(is.na(query$vars$values))){
    triples_values=query$vars %>% 
       dplyr::filter(!is.na(values)) %>% 
       dplyr::mutate(triple=values,
                     required=TRUE,
                     from=glitter:::question_mark(name),
                     to=values,
                     link="values in") %>% 
       dplyr::select(triple, required, from, to, link)
    triples=dplyr::bind_rows(triples,triples_values)
    # Reorder triples by location in query:
    triples=query$vars %>%
     dplyr::mutate(triple=dplyr::case_when(!is.na(values)~values,
                                           TRUE~triple)) %>% 
     dplyr::select(triple) %>% 
     unique() %>% 
     dplyr::left_join(triples,by="triple")
  } 

  triples = triples  %>% 
     dplyr::mutate(step=1:dplyr::n(),
                    filtered=FALSE) 
  if(labelling){
      triples=triples %>% 
         tidyr::pivot_longer(c("from","to","link"),
                          names_to="type",
                          values_to="label") %>%
         dplyr::mutate(label=sequins:::replace_label(label,set_labels)) %>% 
         dplyr::mutate(label=purrr::map_chr(label,
                                     get_label,
                                     language="en",
                                     endpoint="wikidata",
                                     label_property="rdfs:label"
                                     )) %>% 
        tidyr::pivot_wider(names_from="type",
                           values_from="label")
  }#if(labelling)
  nodes=tibble::tibble(
    name=c(triples$from,triples$to),
    step=c(triples$step,triples$step)) %>% 
    dplyr::mutate(type=stringr::str_detect(name,"^\\s*\\?")) %>% 
    dplyr::mutate(type=dplyr::case_when(type~"unknown",
                                             !type~"set")) %>%
    dplyr::group_by(name,type) %>% 
    dplyr::summarise(step=min(step),.groups="drop") %>% 
    dplyr::arrange(step)
  
  nsteps=max(nodes$step, na.rm=TRUE)
  graph=tidygraph::tbl_graph(edges=triples,nodes=nodes) 
  # If there are calls to spq_filter:
  # if(!is.null(query$filters)){
  #   for (i in 1:nrow(query$filters)){
  #     new_triple=tibble::tibble(
  #                       required=TRUE,
  #                       from=query$filters$var[i],
  #                       to=paste0(" ",query$filters$var[i]," "),
  #                       link=query$filters$filter[i])
  #     triples=dplyr::bind_rows(triples,
  #                              new_triple)
  #   }
  # }
  # if(!is.null(query$filters)){
  #   graph=graph %>% 
  #     tidygraph::activate(nodes) %>% 
  #     dplyr::mutate(filtered=dplyr::case_when(name %in% query$filters$var ~ TRUE,
  #                                    TRUE ~ FALSE))
  # }
  # tib_values=query$vars %>% 
  #   dplyr::filter(!is.na(values))
  # if(nrow(tib_values)>0){
  #   for (i in 1:nrow(tib_values)){
  #      var=paste0("?",tib_values$name[i])
  #      graph=graph %>% 
  #         tidygraph::activate(nodes) %>% 
  #         dplyr::mutate(type=dplyr::case_when(name==var~"set",
  #                                             TRUE~type))      
  #   }
  # }
  return(list(graph=graph, nsteps=nsteps))
}
