# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Plot query step as a graph.
#' @param graph a tidygraph object
#' @param plotstep the step to plot
#' @param layout type of layout. Can be e.g. "fr" or "tree". Defaults to "tree"
#' @param flip whether to flip the coordinates. Defaults to FALSE
#' @param legend whether to draw a legend. Defaults to FALSE 
#' @return a plot of the graph depicting query setp
#' 
#' @export
#' @examples
#' plot_query_step()
plot_query_step <- function(graph,plotstep, layout="tree",flip=FALSE, legend=FALSE){
      margin10=ggplot2::margin(10,10,10,10,"mm")
      margin20=ggplot2::margin(20,20,20,20,"mm")
      
      graph=graph %>% 
          tidygraph::activate(nodes) %>% 
          dplyr::mutate(show=step<=plotstep) %>% 
          dplyr::mutate(name=dplyr::case_when(step>plotstep~"",
                                               TRUE~name))
      graph=graph %>% 
          tidygraph::activate(edges) %>% 
          dplyr::mutate(show=step<=plotstep)%>% 
          dplyr::mutate(link=dplyr::case_when(step>plotstep~"",
                                               TRUE~link))
      
      graph_layout=ggraph::create_layout(graph, layout=layout)
      graphplot=ggraph::ggraph(graph_layout)+
        # edges
        ggraph::geom_edge_link(
          ggplot2::aes(label=link,
                       label_size=3,
                       alpha=show,
                       end_cap=ggraph::label_rect(to, padding=margin10)),
          angle_calc = 'along',
          label_dodge = grid::unit(2.5, 'mm'),
          arrow = ggplot2::arrow(length = grid::unit(6, 'mm')),
          )+
        # nodes
        ggraph::geom_node_label(ggplot2::aes(label=name,
                                             fill=type,
                                             color=show,
                                             alpha=show))+
        ggraph::theme_graph(plot_margin=margin20)+
        ggplot2::coord_cartesian(clip="off")+
        ggplot2::scale_alpha_manual(breaks=c(TRUE,FALSE),
                                    values=c(1,0))+
        ggplot2::scale_color_manual(breaks=c(TRUE,FALSE),
                                    values=c("black","white"))+
        ggplot2::guides(alpha="none")
      if(flip){
        graphplot=graphplot +
          ggplot2::coord_flip()+
          ggplot2::scale_y_reverse()+
          ggplot2::scale_x_reverse()
      }
      if(!legend){
        graphplot=graphplot+
          ggplot2::theme(legend.position="none")
      } 
      return(graphplot)
}
