# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Plot query as a graph.
#' @param query a query as returned by glitter (before call to spq_perform)
#' @param labelling whether to label the identifiers in the graph
#' @param language the language in which to label. Defaults to English ("en")
#' @param set_labels a named vector to replace some elements with a user-defined label. For instance, c("hal:structure"="id de labo")
#' @param layout type of layout. Can be e.g. "fr" or "tree". Defaults to "tree"
#' @param flip whether to flip the coordinates. Defaults to FALSE
#' @param legend whether to draw a legend. Defaults to FALSE 
#' @return a plot of the graph depicting query
#' 
#' @export
plot_query <- function(query,labelling=FALSE,language="en",set_labels=NULL,layout="tree",flip=FALSE, legend=FALSE,show_step=FALSE){
  g=graph_query(query=query,
                labelling=labelling,
                language=language,
                set_labels=set_labels)
  nsteps=g$nsteps
  if(show_step){
    result=vector(mode="list",length=nsteps)
        for (i in 1:nsteps){
            graphi=g$graph
            graphplot=plot_query_step(graph=graphi,plotstep=i)
            result[[i]]=graphplot
        }
  }else{
    result=plot_query_step(graph=g$graph,plotstep=nsteps)
  }
  return(result)
}
