# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Based on a list of values surrounded by curly brackets, returns printable list.
#' @param values the values surrounded by curly brackets
#' @return the printable list
#' 
#' @noRd
#' @examples
#' print_values()
print_values=function(values){
       result=values %>% 
           stringr::str_replace_all("(\\{)|(\\})","") %>% 
           stringr::str_split(" ") %>%
          .[[1]]
       return(result)
}
      
