# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Based on a list of values surrounded by curly brackets, returns printable list.
#' @param values the values surrounded by curly brackets
#' @return the printable list
#' 
#' @noRd
#' @examples
#' sequins:::print_values("wdt:P31/wdt:P279*")
#' sequins:::print_values("{wd:Q144 wd:Q146 wd:Q780}")
print_values=function(values){
    result=values %>% 
      glitter:::str_replace_all("/","|") %>% 
      glitter:::str_replace_all("\\*","") %>% 
      glitter:::str_replace_all("(\\{)|(\\})","") %>% 
      glitter:::str_split("( )|(\\|)")
      return(result)
}
