# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Replaces label with new label if label corresponds to one of the names of set_labels
#' @param label a string to maybe replace
#' @param set_labels a named vector with previous labels as names and new labels as values.
#' @return a possibly new label
#' 
#' @noRd
#' @examples
#' sequins:::replace_label("hal:structure",c("hal:structure"="id de labo"))
#' sequins:::replace_label(c("tuttut","pouetpouet","ouiiiink"),
#'                         c("tuttut"="klaxon","pouetpouet"="corne de brume"))
replace_label=function(label,set_labels){
  replace_one_label=function(one_label,set_labels){
    if(one_label %in% names(set_labels)){
      index=which(names(set_labels)==one_label)
      return(set_labels[[index]])
    }else{return(one_label)}
  }
  result=purrr::map_chr(label,replace_one_label,set_labels)
  return(result)
}
